USE sql_forda;

DROP TABLE IF EXISTS REGEXP_TABLE;
CREATE TABLE REGEXP_TABLE (ID INT, FULLNAME VARCHAR(100), EMAIL VARCHAR(100), SALARY INT);
-- Insert 10 sample records (with 1 NULL EMAIL and 1 NULL SALARY)
INSERT INTO REGEXP_TABLE VALUES
(1, 'Alice Johnson',   'alice123@gmail.com',   75000),
(2, 'Bob Smith',       'bob@yahoo.com',        60000),
(3, 'Carol99',         'carol_99@gmail.com',   82000),
(4, 'David Green',     'david@org.org',        90000),
(5, 'Eve_Lane',        NULL,                   70000),
(6, 'Frank O''Neill',  'frank.oneill@pro.net', NULL),
(7, 'Grace Hopper',    'grace_h@abc.com',      95000),
(8, 'Heidi',           'heidi@domain.co',      88000),
(9, 'Isaac_007',       'isaac007@site.io',     87000),
(10, 'John',           'john@apple.com',       92000);

-- REGEXP Queries

SELECT * FROM REGEXP_TABLE WHERE EMAIL REGEXP '\\.com$';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '^[AC]';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '[0-9]$';
SELECT * FROM REGEXP_TABLE WHERE EMAIL REGEXP '[0-9]';
SELECT * FROM REGEXP_TABLE WHERE EMAIL REGEXP '_';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME NOT REGEXP ' ';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '.+';
SELECT * FROM REGEXP_TABLE WHERE EMAIL REGEXP '^[a-zA-Z]';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP 'o.';
SELECT * FROM REGEXP_TABLE WHERE EMAIL REGEXP 'gmail';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '[a-z]{3,}';
SELECT * FROM REGEXP_TABLE WHERE EMAIL REGEXP '\\.(?!com$)';
SELECT * FROM REGEXP_TABLE WHERE EMAIL REGEXP '^[a-z]+@';
SELECT * FROM REGEXP_TABLE WHERE EMAIL IS NOT NULL AND EMAIL REGEXP '.+';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '^[A-Za-z]+ [A-Za-z]+$';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '[^A-Za-z0-9 ]';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '^[A-Za-z0-9 ]+$';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '^[A-Za-z ]+$';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '^[A-Za-z]+$';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '[A-Z]';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '[a-z]';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '[A-Z]' AND FULLNAME REGEXP '[a-z]';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '[0-9]';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '^[A-Za-z]+( [A-Za-z]+){2,}$';
SELECT * FROM REGEXP_TABLE WHERE FULLNAME REGEXP '^[A-Z][a-z]+( [A-Z][a-z]+)?$';











